spring.application.name=08_2_microservicio_crud_productos_reactivo_securizado_JWT
server.port=7010
clave=08_2_microservicio_crud_productos_reactivo_securizado_JWT08_2_microservicio_crud_productos_reactivo_securizado_JWT
